package com.example.shelterforpets.constants;

public enum Step {
    START_MENU,
    CAT_SHELTER_MENU,
    DOG_SHELTER_MENU,
    CAT_SHELTER_INFO_MENU,
    DOG_SHELTER_INFO_MENU,
    CAT_SHELTER_CONSULTATION_MENU,
    DOG_SHELTER_CONSULTATION_MENU
}
